### PR TITLE
breaking: bump `starknet-rs` to `0.11.0` + migrate to the new `Felt` type 

### PR DESCRIPTION
**Pull request by kariy**
~~**UPDATE**: waiting on https://github.com/xJonathanLEI/starknet-rs/pull/612~~

Changes:

- use versioned execution types; replacing all references to `Account::execute()` and `Execution` (which are now considered deprecated) to the `Account::execute_v1()` and `ExecutionV1` respectively.
 
https://github.com/xJonathanLEI/starknet-rs/blob/016f3ee3293c8355f8a7cb64777adea6119493b9/starknet-accounts/src/account/mod.rs#L58-L60

- replace the old `FieldElement` to `Felt`.
- downstream uses of `abigen!` now requires adding the `num-traits` crate as a dependencies.

### CODE REVIEW

**Comment by xJonathanLEI** [comment]
You need a patch release on `starknet-core`?

**Comment by kariy** [comment]
> You need a patch release on `starknet-core`?

yes, that'd be very helpful

**Comment by xJonathanLEI** [comment]
`starknet-core` v0.11.1 is now available on crates.io.

**Review by glihm — APPROVED** [review]
thanks for the work here @kariy! 🚀

**Pull request merged**
